version: '3.8'

services:
  app:
    image: my-spring-boot-app:latest
    container_name: spring-boot-app
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
